# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1500, 900)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1500, 900))
        self.widget_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1500, 900))
        self.label_4.setStyleSheet("border-image: url(:/images/html-css-collage-concept-with-hacker.jpg);\n"
"border-radius:20px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 1500, 900))
        self.label_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius:20px;")
        self.label_7.setText("")
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.backButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.backButton_2.setGeometry(QtCore.QRect(20, 820, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton_2.setFont(font)
        self.backButton_2.setStyleSheet("border-image: url(:/images/images.jpeg);\n"
"border-radius:20px")
        self.backButton_2.setText("")
        self.backButton_2.setObjectName("backButton_2")
        self.titleframe = QtWidgets.QFrame(self.widget_2)
        self.titleframe.setGeometry(QtCore.QRect(0, 0, 1500, 90))
        self.titleframe.setStyleSheet("border-radius:20px;")
        self.titleframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleframe.setObjectName("titleframe")
        self.minimizeButton_2 = QtWidgets.QPushButton(self.titleframe)
        self.minimizeButton_2.setGeometry(QtCore.QRect(1370, 20, 51, 41))
        self.minimizeButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/chrome-minimize-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton_2.setIcon(icon)
        self.minimizeButton_2.setIconSize(QtCore.QSize(40, 40))
        self.minimizeButton_2.setObjectName("minimizeButton_2")
        self.label_9 = QtWidgets.QLabel(self.titleframe)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 60, 60))
        self.label_9.setStyleSheet("image: url(:/images/logoimgae.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.titleframe)
        self.label_10.setGeometry(QtCore.QRect(380, 30, 731, 50))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgba(255,255,255,210);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.closeButton_2 = QtWidgets.QPushButton(self.titleframe)
        self.closeButton_2.setGeometry(QtCore.QRect(1430, 20, 51, 41))
        self.closeButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/—Pngtree—check mark and cross gradient_15118783.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton_2.setIcon(icon1)
        self.closeButton_2.setIconSize(QtCore.QSize(36, 36))
        self.closeButton_2.setObjectName("closeButton_2")
        self.histogramButton = QtWidgets.QPushButton(self.widget_2)
        self.histogramButton.setGeometry(QtCore.QRect(1060, 630, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.histogramButton.setFont(font)
        self.histogramButton.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"   color:rgba(255, 255, 255, 210);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"   }\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.histogramButton.setObjectName("histogramButton")
        self.histogramLabel = QtWidgets.QLabel(self.widget_2)
        self.histogramLabel.setGeometry(QtCore.QRect(840, 140, 600, 450))
        self.histogramLabel.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:15px;")
        self.histogramLabel.setText("")
        self.histogramLabel.setObjectName("histogramLabel")
        self.StegoimageButton = QtWidgets.QPushButton(self.widget_2)
        self.StegoimageButton.setGeometry(QtCore.QRect(510, 500, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.StegoimageButton.setFont(font)
        self.StegoimageButton.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"   color:rgba(255, 255, 255, 210);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"   }\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.StegoimageButton.setObjectName("StegoimageButton")
        self.cleanimageButton = QtWidgets.QPushButton(self.widget_2)
        self.cleanimageButton.setGeometry(QtCore.QRect(130, 510, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cleanimageButton.setFont(font)
        self.cleanimageButton.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"   color:rgba(255, 255, 255, 210);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"   }\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.cleanimageButton.setObjectName("cleanimageButton")
        self.cleanImageLabel = QtWidgets.QLabel(self.widget_2)
        self.cleanImageLabel.setGeometry(QtCore.QRect(80, 140, 350, 350))
        self.cleanImageLabel.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:15px;")
        self.cleanImageLabel.setText("")
        self.cleanImageLabel.setObjectName("cleanImageLabel")
        self.stegoImageLabel = QtWidgets.QLabel(self.widget_2)
        self.stegoImageLabel.setGeometry(QtCore.QRect(460, 140, 350, 350))
        self.stegoImageLabel.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:15px;")
        self.stegoImageLabel.setText("")
        self.stegoImageLabel.setObjectName("stegoImageLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_10.setText(_translate("Dialog", "Statistical Analysis - Detection Via Histogram"))
        self.histogramButton.setText(_translate("Dialog", "DETECT"))
        self.StegoimageButton.setText(_translate("Dialog", "SELECT STEGO IMAGE"))
        self.cleanimageButton.setText(_translate("Dialog", "SELECT CLEAN IMAGE"))
import source_img_rc
